from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Iterable

DEFAULT_INPUT_DIR = "知识图谱构建数据集"
DEFAULT_OUTPUT_DIR = "data/cleaned"
SENTENCE_FILE = "sentences.jsonl"


def normalize_text(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t\u3000]+", " ", text)
    text = re.sub(r"\n{2,}", "\n", text)
    return text.strip()


def is_toc_line(line: str) -> bool:
    if "目录" in line:
        return True
    if re.search(r"\.{2,}\s*\d+$", line):
        return True
    if re.search(r"…{2,}\s*\d+$", line):
        return True
    return False


def is_boilerplate_line(line: str) -> bool:
    lower = line.lower()
    keywords = [
        "document generated by",
        "annas archive",
        "filename_decoded",
        "filesize",
        "md5",
        "sha1",
        "sha256",
        "crc32",
        "zip_password",
        "uncompressed_size",
        "pdg_main_pages",
        "total_pages",
        "total_pixels",
        "pdf_generation",
        "pdg_dir_name",
    ]
    return any(keyword in lower for keyword in keywords)


def is_pdf_glyph_line(line: str) -> bool:
    tokens = re.findall(r"/[A-Za-z]{1,3}\d{0,3}", line)
    if len(tokens) >= 3:
        non_space = re.sub(r"\s+", "", line)
        token_chars = sum(len(token) for token in tokens)
        if token_chars / max(len(non_space), 1) > 0.4:
            return True
    return False


def is_garbled_line(line: str) -> bool:
    stripped = line.strip()
    if len(stripped) < 2:
        return True
    if is_pdf_glyph_line(stripped):
        return True
    non_space = re.sub(r"\s+", "", stripped)
    if not non_space:
        return True
    if re.fullmatch(r"[\d\W_]+", non_space):
        return True
    valid = re.findall(r"[A-Za-z0-9\u4e00-\u9fff]", non_space)
    ratio = len(valid) / max(len(non_space), 1)
    return ratio < 0.3


def clean_lines(text: str) -> tuple[str, int, int]:
    lines = text.split("\n")
    kept: list[str] = []
    toc_count = 0
    for line in lines:
        line = line.strip()
        if not line:
            continue
        if is_boilerplate_line(line):
            continue
        if is_toc_line(line):
            toc_count += 1
            continue
        if is_garbled_line(line):
            continue
        kept.append(line)
    return "\n".join(kept), toc_count, len(kept)


def is_low_quality_text(text: str) -> bool:
    compact = re.sub(r"\s+", "", text)
    if len(compact) < 30:
        return True
    valid = re.findall(r"[A-Za-z0-9\u4e00-\u9fff]", compact)
    ratio = len(valid) / max(len(compact), 1)
    return ratio < 0.2


def split_sentences(text: str) -> list[str]:
    text = text.replace("\n", "\n")
    parts = re.split(r"(?<=[。！？!?；;])\s*", text)
    sentences: list[str] = []
    for part in parts:
        for line in part.split("\n"):
            sentence = line.strip()
            if sentence:
                sentences.append(sentence)
    return sentences


def iter_text_files(input_dir: Path) -> Iterable[Path]:
    for path in input_dir.rglob("*"):
        if path.is_file() and path.suffix.lower() in {".txt", ".md", ".pdf"}:
            yield path


def read_pdf_pages(file_path: Path) -> list[str]:
    try:
        from pypdf import PdfReader
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "Missing dependency 'pypdf'. Install with: pip install pypdf"
        ) from exc

    reader = PdfReader(str(file_path))
    pages: list[str] = []
    for page in reader.pages:
        page_text = page.extract_text() or ""
        pages.append(page_text)
    return pages


def preprocess(input_dir: Path, output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    sentences_path = output_dir / SENTENCE_FILE
    with sentences_path.open("w", encoding="utf-8") as writer:
        for file_path in iter_text_files(input_dir):
            rel_path = file_path.relative_to(input_dir)
            source_category = rel_path.parts[0] if rel_path.parts else ""
            if file_path.suffix.lower() == ".pdf":
                cleaned_path = (output_dir / rel_path).with_suffix(".txt")
                pages = read_pdf_pages(file_path)
                cleaned_path.parent.mkdir(parents=True, exist_ok=True)
                cleaned_pages: list[str] = []
                for page_index, page_text in enumerate(pages):
                    normalized = normalize_text(page_text)
                    cleaned, toc_count, kept_count = clean_lines(normalized)
                    if toc_count >= 5 and toc_count > kept_count:
                        continue
                    if cleaned and not is_low_quality_text(cleaned):
                        cleaned_pages.append(cleaned)
                        sentences = split_sentences(cleaned)
                        for idx, sentence in enumerate(sentences):
                            record = {
                                "id": f"{rel_path.as_posix()}::p{page_index}::{idx}",
                                "sentence": sentence,
                                "source_file": rel_path.as_posix(),
                                "source_category": source_category,
                                "source_page_index": page_index,
                                "source_page_number": page_index + 1,
                                "index": idx,
                            }
                            writer.write(json.dumps(record, ensure_ascii=False) + "\n")
                if cleaned_pages:
                    cleaned_path.write_text("\n".join(cleaned_pages), encoding="utf-8")
                elif cleaned_path.exists():
                    cleaned_path.unlink()
            else:
                cleaned_path = output_dir / rel_path
                cleaned_path.parent.mkdir(parents=True, exist_ok=True)
                text = file_path.read_text(encoding="utf-8", errors="ignore")
                cleaned = normalize_text(text)
                cleaned, _, _ = clean_lines(cleaned)
                if not cleaned or is_low_quality_text(cleaned):
                    if cleaned_path.exists():
                        cleaned_path.unlink()
                    continue
                cleaned_path.write_text(cleaned, encoding="utf-8")
                sentences = split_sentences(cleaned)
                for idx, sentence in enumerate(sentences):
                    record = {
                        "id": f"{rel_path.as_posix()}::{idx}",
                        "sentence": sentence,
                        "source_file": rel_path.as_posix(),
                        "source_category": source_category,
                        "index": idx,
                    }
                    writer.write(json.dumps(record, ensure_ascii=False) + "\n")
    return sentences_path


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Preprocess raw texts and split sentences.")
    parser.add_argument("--input", default=DEFAULT_INPUT_DIR, help="Input dataset directory")
    parser.add_argument("--output", default=DEFAULT_OUTPUT_DIR, help="Output cleaned directory")
    return parser


def main() -> None:
    parser = build_arg_parser()
    args = parser.parse_args()
    input_dir = Path(args.input)
    output_dir = Path(args.output)
    if not input_dir.exists():
        raise SystemExit(f"Input directory not found: {input_dir}")
    sentences_path = preprocess(input_dir, output_dir)
    print(f"Sentences saved to {sentences_path}")


if __name__ == "__main__":
    main()
